export const occasionOptions = [
	{ label: 'Anniversary', value: 'woman' },
	{ label: 'Baby Shower', value: 'male' },
	{ label: 'Birthday', value: 'male' },
	{ label: 'Bridal Shower', value: 'male' },
	{ label: 'Christmas', value: 'male' },
	{ label: 'Congratulations', value: 'male' },
	{ label: 'Engagement', value: 'male' },
	{ label: 'Father’s Day', value: 'male' },
	{ label: 'Friendship', value: 'male' },
	{ label: 'Friendship', value: 'male' },
	{ label: 'Graduation', value: 'male' },
	{ label: 'Grandparents Day', value: 'male' },
	{ label: 'Halloween', value: 'male' },
	{ label: 'Hanukkah', value: 'male' },
	{ label: 'Housewarming', value: 'male' },
	{ label: 'Independence Day', value: 'male' },
	{ label: 'Love', value: 'male' },
	{ label: 'Miss You', value: 'male' },
	{ label: 'Mother’s Day', value: 'male' },
	{ label: 'National Boss Day', value: 'male' },
	{ label: 'New Baby', value: 'male' },
	{ label: 'New Year’s', value: 'male' },
	{ label: 'Pregnancy', value: 'male' },
	{ label: 'Retirement', value: 'male' },
	{ label: 'Sorry', value: 'male' },
	{ label: 'St. Patrick’s Day', value: 'male' },
	{ label: 'Sympathy', value: 'male' },
	{ label: 'Teacher Appreciation', value: 'male' },
	{ label: 'Thank You', value: 'male' },
	{ label: 'Thanksgiving', value: 'male' },
	{ label: 'Thinking of You', value: 'male' },
	{ label: 'Valentine’s Day', value: 'male' },
	{ label: 'Veterans Day', value: 'male' },
	{ label: 'Wedding', value: 'male' },
]

export const genderOptions = [
	{ label: 'Woman', value: 'woman' },
	{ label: 'Male', value: 'male' },
	{ label: 'Custom', value: 'non-binary-person' },
]
